#!/usr/bin/env bash
# exp6_verus_vacuity_probe.sh
# ===========================
# Reviewer experiment 6 -- "Does 'verification results:: 15 verified, 0 errors'
# mean what the paper implies it means?"
#
# Requires: verus on PATH (the paper's pin: 0.2026.05.03.8b81855), and the
# artifact repo (crates/remit/proof/*.rs).
#
# Four steps:
#   1. REPRODUCE the paper's tallies on the three shipped proof files
#      (expected 9 / 4 / 15 verified, 0 errors). Credit where due.
#   2. EXHIBIT, verbatim with line numbers, that the foregrounded FD lemma
#      and the PC lemmas ship with EMPTY proof bodies -- the checker needs
#      zero argument from the author because ensures unfolds to requires.
#   3. EMPTY-BODY PROBE for RD: strip the single assert from each RD lemma
#      body and re-verify. If a "theorem" verifies with an empty body, it
#      carries no proof burden: RD "order-independence" is congruence over a
#      recover() that was DEFINED to factor through the multiset.
#   4. ADVERSARIAL-DEFINITION PROBE for FD: state the very same lemma shape
#      against the STOCK LangGraph serving rule (#6663: every invocation is
#      served the first recorded value). Verus must REJECT it (expected:
#      "1 verified, 1 error"). Conclusion: the shipped FD lemma passes only
#      because served() was DEFINED as the correct keyed lookup -- the
#      "proof" could never have caught the very bug the paper is about.
#
# Usage:
#   REPO=/path/to/repo bash exp6_verus_vacuity_probe.sh
# (REPO defaults to . ; probes are generated into ./exp6_probes/)

set -u
REPO="${REPO:-${1:-.}}"

# ---- locate the proof directory -------------------------------------------
PROOF=""
for c in "$REPO/crates/remit/proof" "$REPO/_extract/crates/remit/proof" \
         "$REPO/repo/_extract/crates/remit/proof"; do
  [ -f "$c/remit_verus.rs" ] && PROOF="$c" && break
done
if [ -z "$PROOF" ]; then
  PROOF="$(find "$REPO" -path '*crates/remit/proof' -type d 2>/dev/null | head -1)"
fi
[ -n "$PROOF" ] && [ -f "$PROOF/remit_verus.rs" ] || {
  echo "ERROR: crates/remit/proof not found under $REPO"; exit 2; }
echo "proof dir: $PROOF"

OUT="./exp6_probes"; mkdir -p "$OUT"

# ---- step 2 exhibit (needs no verus) --------------------------------------
echo
echo "=============================================================================="
echo " 2. THE FD LEMMA, VERBATIM FROM THE SHIPPED FILE (note the empty body)"
echo "=============================================================================="
grep -n -A 11 "fn lemma_fd_distinct_values_served_distinctly" "$PROOF/remit_verus.rs"
echo
echo "   served() is defined three lines above it as:  supplied[ordinal]"
echo "   => ensures  served(s,o1) != served(s,o2)  unfolds to the requires"
echo "      s[o1] != s[o2].  P => P.  Body is {} because nothing is proved."
echo
echo "   PC lemmas (same file): commit(f,t) == t, admissible iff t == f+1,"
echo "   ensures t > f  -- linear arithmetic, empty bodies:"
grep -n -A 4 "fn lemma_pc_strict_monotone\|fn lemma_pc_no_prefix_reentry" "$PROOF/remit_verus.rs" | sed 's/^/   /'

# ---- generate probe files (needs no verus) --------------------------------
python3 - "$PROOF" "$OUT" <<'PYEOF'
import re, sys
proof, out = sys.argv[1], sys.argv[2]
src = open(f"{proof}/remit_verus_cv_rd.rs").read()

b1 = "{\n    assert(a.records == b.records);\n}"
b2 = "{\n    assert(a.records.to_multiset() == b.records.to_multiset());\n}"
assert src.count(b1) == 1, "RD-1 body not found verbatim; file drifted"
assert src.count(b2) == 1, "RD-2 body not found verbatim; file drifted"

open(f"{out}/probe_rd1_empty.rs", "w").write(
    src.replace(b1, "{\n}", 1))
open(f"{out}/probe_rd2_empty.rs", "w").write(
    src.replace(b2, "{\n}", 1))

probe_fd = '''// probe_fd_stock_rule.rs -- generated by exp6.
// Same lemma SHAPE as lemma_fd_distinct_values_served_distinctly, stated
// twice: against the keyed rule the paper verifies (identity lookup), and
// against the STOCK LangGraph #6663 rule (serve the first recorded value).
// Expected: "1 verified, 1 error" -- fd_keyed passes with an empty body
// (the tautology, replicated), fd_stock is REJECTED (FD is false there).
use vstd::prelude::*;

verus! {

// The rule the paper verifies: identity lookup. FD-by-definition.
pub open spec fn served_keyed(supplied: Map<nat, nat>, ordinal: nat) -> nat
    recommends supplied.dom().contains(ordinal)
{
    supplied[ordinal]
}

// The stock rule (#6663): every invocation is served ordinal 0's value.
pub open spec fn served_stock(supplied: Map<nat, nat>, ordinal: nat) -> nat
    recommends supplied.dom().contains(0)
{
    supplied[0]
}

proof fn fd_keyed(supplied: Map<nat, nat>, o1: nat, o2: nat)
    requires
        supplied.dom().contains(o1),
        supplied.dom().contains(o2),
        supplied[o1] != supplied[o2],
    ensures
        served_keyed(supplied, o1) != served_keyed(supplied, o2),
{
}

proof fn fd_stock(supplied: Map<nat, nat>, o1: nat, o2: nat)
    requires
        supplied.dom().contains(0),
        supplied.dom().contains(o1),
        supplied.dom().contains(o2),
        supplied[o1] != supplied[o2],
    ensures
        served_stock(supplied, o1) != served_stock(supplied, o2),
{
}

fn main() {}

} // verus!
'''
open(f"{out}/probe_fd_stock_rule.rs", "w").write(probe_fd)
print("generated: probe_rd1_empty.rs probe_rd2_empty.rs probe_fd_stock_rule.rs")
PYEOF
[ $? -eq 0 ] || { echo "probe generation failed"; exit 2; }

# ---- verus available? ------------------------------------------------------
if ! command -v verus >/dev/null 2>&1; then
  echo
  echo "verus not on PATH: probes generated in $OUT/ -- install/point to the"
  echo "paper's pinned toolchain (0.2026.05.03.8b81855) and re-run this script."
  exit 3
fi

vrun () { verus "$1" 2>&1 | grep -E "verification results|error\[|error:" | head -4; }

echo
echo "=============================================================================="
echo " 1. REPRODUCE THE PAPER'S TALLIES (expected 9 / 4 / 15 verified, 0 errors)"
echo "=============================================================================="
for f in remit_verus.rs remit_verus_cv_rd.rs remit_verus_all.rs; do
  printf "   %-24s " "$f:"; vrun "$PROOF/$f"
done

echo
echo "=============================================================================="
echo " 3. RD EMPTY-BODY PROBES (a theorem that verifies with body {} proves"
echo "    the checker needed nothing from the author)"
echo "=============================================================================="
printf "   %-24s " "probe_rd1_empty.rs:"; R1="$(vrun "$OUT/probe_rd1_empty.rs")"; echo "$R1"
printf "   %-24s " "probe_rd2_empty.rs:"; R2="$(vrun "$OUT/probe_rd2_empty.rs")"; echo "$R2"
echo
echo "   Reading: recover(log) is DEFINED as recover_of_writeset(to_multiset(log))"
echo "   with recover_of_writeset uninterpreted. 'Order-independence' is therefore"
echo "   g(m) == g(m) -- congruence over a definition that already erased order."
echo "   If a probe above still needs its one-line assert, that assert (=~= to =="
echo "   promotion) is the ENTIRE mathematical content of the 'theorem'."

echo
echo "=============================================================================="
echo " 4. ADVERSARIAL-DEFINITION PROBE (expected: 1 verified, 1 error)"
echo "=============================================================================="
printf "   %-24s " "probe_fd_stock_rule.rs:"; R4="$(verus "$OUT/probe_fd_stock_rule.rs" 2>&1)"
echo "$R4" | grep -E "verification results" | head -1
echo "$R4" | grep -B1 -A2 "fd_stock" | head -8 | sed 's/^/   /'
echo
if echo "$R4" | grep -q "1 verified" && echo "$R4" | grep -qE "1 error"; then
  echo "   CONFIRMED: fd_keyed passes with an EMPTY body (the shipped tautology,"
  echo "   replicated); fd_stock -- the same lemma shape against the actual #6663"
  echo "   serving rule -- is REJECTED. The shipped FD 'proof' passes because the"
  echo "   definition of served() IS the property. It could not have detected the"
  echo "   bug this paper exists to fix, even in the abstract."
else
  echo "   UNEXPECTED tally -- inspect $OUT/probe_fd_stock_rule.rs output above."
  echo "   (Expected fd_keyed to verify and fd_stock to fail its postcondition.)"
fi

echo
echo "=============================================================================="
echo " WHAT A NON-VACUOUS VERSION LOOKS LIKE (paper fix, not run here)"
echo "=============================================================================="
cat <<'TXT'
   Model serving as a STATE MACHINE (record step + serve step), prove the
   invariant "every recorded ordinal maps to the value its own invocation
   supplied", and derive FD from that invariant -- so that swapping in the
   stock precedence rule (serve first recorded) FALSIFIES the invariant at
   the record/serve step. Then connect it to code: annotate
   crates/remit/src/lib.rs itself (exec fns with ensures) or exhibit a
   refinement from this model to remit-core. Until one of those exists,
   write "15 verified items" as what it is: a machine-checked SPECIFICATION
   whose FD/RD/PC content is definitional, plus genuine-but-elementary
   EO/CO/CV lemmas, none attached to shipped code.
TXT
