// probe_fd_stock_rule.rs -- generated by exp6.
// Same lemma SHAPE as lemma_fd_distinct_values_served_distinctly, stated
// twice: against the keyed rule the paper verifies (identity lookup), and
// against the STOCK LangGraph #6663 rule (serve the first recorded value).
// Expected: "1 verified, 1 error" -- fd_keyed passes with an empty body
// (the tautology, replicated), fd_stock is REJECTED (FD is false there).
use vstd::prelude::*;

verus! {

// The rule the paper verifies: identity lookup. FD-by-definition.
pub open spec fn served_keyed(supplied: Map<nat, nat>, ordinal: nat) -> nat
    recommends supplied.dom().contains(ordinal)
{
    supplied[ordinal]
}

// The stock rule (#6663): every invocation is served ordinal 0's value.
pub open spec fn served_stock(supplied: Map<nat, nat>, ordinal: nat) -> nat
    recommends supplied.dom().contains(0)
{
    supplied[0]
}

proof fn fd_keyed(supplied: Map<nat, nat>, o1: nat, o2: nat)
    requires
        supplied.dom().contains(o1),
        supplied.dom().contains(o2),
        supplied[o1] != supplied[o2],
    ensures
        served_keyed(supplied, o1) != served_keyed(supplied, o2),
{
}

proof fn fd_stock(supplied: Map<nat, nat>, o1: nat, o2: nat)
    requires
        supplied.dom().contains(0),
        supplied.dom().contains(o1),
        supplied.dom().contains(o2),
        supplied[o1] != supplied[o2],
    ensures
        served_stock(supplied, o1) != served_stock(supplied, o2),
{
}

fn main() {}

} // verus!
